### ISSUE TITLE
problems browsing through dlna directories

### ISSUE THREAD

**Issue by daebenji** [chachmu/mpvDLNA#3]
Hello,

i'm using the latest version of your plugin, but having problems to browse through the folders of my dlna (minidlna). 
I have to mention, that the same config does work without any problems on windows 10 but there is a problem on linux. It seems that it has to do with the slicing of '\n'.

I already changed:
`221  var server = new DLNA_Server(sp[i].slice(0, -1), sp[i+1].slice(0, -1));`
to 
`221  var server = new DLNA_Server(sp[i], sp[i+1]);`

With this change, i was able to navigate to the first level of the server, and actually choosing it. The name of the server i want to browse is RPi3 but before the change it was only displayed as RPi and I was not able to go deeper into the structure behind it. Now I can select it and see the second level but there are also some chars missing and i can not choose "Browse Folder" or any other selectable items. Please see also attached screenshot, which shows the missing character for "Browse Folders", "Music", "Pictures"  and "Video" - missing always the last character.
![pic-window-210511-0950-56](https://user-images.githubusercontent.com/4353351/117779622-21854d00-b23f-11eb-866b-4d5f22f8a5f2.png)

**Comment by chachmu** [comment]
Sorry I missed this issue, I thought I had github notifications turned on but apparently not. As far as your issue goes, if the newline slicing is the problem then it is possible that you fixed the issue in the function that detects and displays servers but didn't make the change in the function that displays the items in the server. I will try to take a closer look at this and get a more versatile fix up tonight or over the weekend.

**Comment by chachmu** [comment]
@daebenji I figured out what was going on and have fixed the issue. Try updating to the new release: [V3.1.3](https://github.com/chachmu/mpvDLNA/releases/tag/V3.1.3) and let me know if it works.

**Comment by daebenji** [comment]
hi, it acually did not change for me.

you can have a look at my screencast at https://odysee.com/@Donk:4/mpvDLNA-v0.1:c

It stucks when selecting the miniDLNA Server. Before I was able to go on level deeper. I took the new release and just changed the controls to vim bindings.

**Comment by chachmu** [comment]
Ok. That video should be pretty helpful because it looks like the UI froze up which was not something I experienced when testing on Ubuntu. I'll try to look into that as well.

**Comment by chachmu** [comment]
@daebenji I still haven't been able to reproduce your new issue. What version of linux are you running? 

Also, I just pushed a new version with more logging options so could you run mpv with the argument `--msg-level=mpvDLNA=trace` and post what it outputs when it gets stuck? Hopefully this will help make it more clear what exactly is going on behind the scenes when it crashes.

**Comment by daebenji** [comment]
Hi, I'm running manjaro (archlinux) and DWM as Window Manager. 
I'm not able to see any output when providing --msg-level=mpvDLNA=trace as argument... Maybe you can assist me, how to use call the functions from command line?

**Comment by daebenji** [comment]
I figured it out myself. I was the problem. Now I have no problems to browse and play content from my dlna server.
Thanks for your support!
