### ISSUE TITLE
Using with libmpv

### ISSUE THREAD

**Issue by ua0lnj** [chachmu/mpvDLNA#4]
Hi.
I want use you plugin, but with libmpv in other apps.
I can't use mpv osd, I create my osd and display it from overlay-add command, in the future, generally output to a separate window.
I need to get info about the dlna servers and it's catalogs/files from libmpv, for example as playlist positions throught mpv_event_property MPV_OBSERVE_LIST_COUNT.
Can you do something like this?

**Comment by chachmu** [comment]
I probably could store the list into [shared-script-properties](https://mpv.io/manual/master/#command-interface-shared-script-properties) and then commands could be passed back through the same interface although this seems overly complicated.

What language are you using to write your code? It might be easier to just call mpvDLNA.py directly. If you are programming in python then you could literally just copy the code and reuse it.

**Comment by ua0lnj** [comment]
I wanted to get by with minimal costs, but apparently I need to write my own code :)
