### ISSUE TITLE
suggestion for instructions (linux)

### ISSUE THREAD

**Issue by dmillfree868** [chachmu/mpvDLNA#5]
I installed mpvDLNA on my windows pc. No problem worked first shot. On Slackware Linux Python 2.7 and Python 3.9 are installed. upnpclient installed to Python 3.9. I used the dbug feature of mpvDLNA and it said no module called upnpclient. I had to edit main.js and change python to python3 and then mpvDLNA worked properly. I know some other Linux distros have a similar python ecosystem, so it may be worthwhile to point out in the install instructions that main.js may need to be edited python>python3. Thanks for creating this plugin, it's awesome!

**Comment by chachmu** [comment]
I'm glad you like the plugin! 

I just added a check on startup to test which name to use between `python` and `python3` when calling python and added an option to the .conf file to specify any arbitrary name. 

If this doesn't work for whatever reason just go ahead and reopen the issue and I'll take a look.
