### ISSUE TITLE
Not detecting SDLNA server / subfolders

### ISSUE THREAD

**Issue by goombapatrol** [chachmu/mpvDLNA#6]
I was really excited to find this script - thanks in advance!

So my setup is SimpleDLNA - it's fast and lightweight, and I've had no issues with any of my other devices detecting or playing media from the server; at first mpvDLNA did not seem to detect it.

Doing some testing, it found PLEX just fine. I tried entering IP manually in the syntax
```
server_names: '{SDLNA}',
server_addrs: '{192.168.1.123:12345}',
```
eventually what worked was a blind
```
server_addrs: '{192.168.1.123:12345/mm-1/description.xml}',
```
After further testing, it seems that the VIEW filter (e.g. sdlna.exe -v music) was what was preventing it from being automatically detected - heads up for anyone out there on similar setup.
![image](https://user-images.githubusercontent.com/7359713/150264205-7fbd5bf2-8853-45cf-b7c8-687a7df8c2f9.png)

So at this point, I could play files in the top level directory, but none of the subfolders appear in the list to pick from.

Flattening all files is a possibility, but leads to messy order (tracks 01 01 01 01 etc) so actual folder browsing support would be desired.

For example, subfolder 'new' URL looks like
http://192.168.1.123:12345/mm-1/index/6B1381F5#0/v:new

I realize this may be an issue on upnpclient's end (inactive project?) but maybe there's still something that can be done. (And let me know if there's any more information I can provide to help.)

Thanks!

**Comment by chachmu** [comment]
I'm glad you like mpvDLNA!

I installed SimpleDLNA and tried running a quick server from my windows machine. It looks like there might be a variety of reasons you were having trouble finding the server on top of just the filter. On my end I had a combination of a decoding issue in the way mpvDLNA lists devices as well as SimpleDLNA being incosistent with very low timeouts while searching for servers. I had already fixed the decoding issue in other places but forgot to fix it in that specific function so I pushed an updated version and also added a config option to use a longer timeout.

As for the issue with the folder layout I haven't been able to replicate it so far. I've tried with both video and audio and the folders seem to be layed out correctly. I also tried using the GUI and the command line versions with and without filtering and didn't have any issues there either.

I did notice that my urls for a subfolder look slightly different: `http://192.168.0.123:61593/mm-1/index/57AA6962`. They don't have the `#0/v:name` on the end although I'm not sure if that would actually matter.

**Comment by goombapatrol** [comment]
Figured it out! It breaks (quits searching?) if the folder specified has any _playable files directly within_. So **-v music** itself wasn't what was breaking it after all.

e.g.
```
C:\folder1 contains: album1 album2
C:\folder2 contains: album1 album2 test.mp3 test2.mp3
```

running sdlna.exe **C:\folder1** shows this
![image](https://user-images.githubusercontent.com/7359713/150602864-a7271536-aa14-4ac1-bd22-8560384a4946.png)

running sdlna.exe **C:\folder2** only shows
![image](https://user-images.githubusercontent.com/7359713/150603160-2887aaba-9756-407d-bcb2-2f79482eec89.png)

(I normally run it with a list of folders, many of which have individual stray files in top level.)

Running on Win 7. I'm using fork https://github.com/hermanho/simpleDLNA (exe in build folder) but have also tested with official binaries (1.0) https://nmaier.github.io/simpleDLNA/

**Comment by chachmu** [comment]
That helps a lot, it probably is an issue with mpvDLNA in that case. I'll take a look and see if I can fix it later tonight.

**Comment by chachmu** [comment]
I think I have fixed the issue with subfolders. Try updating to the newest release ([V3.3.0](https://github.com/chachmu/mpvDLNA/releases/tag/V3.3.0)). If that doesn't work just let me know and I can take another look at it.

**Comment by goombapatrol** [comment]
Nice work! That did the trick, files and folders showing up as expected now. (_Albums/Folders/Genre_ etc are at the bottom - a minor quirk, but if they could appear first at top that would be cleaner.)

Unfortunately still seems to not find (at least when -v music filter is on) the server automatically. 
Increasing node count (is that for speed?) and 30s timeout didn't make make a difference there.

Config file seemed like the best option for now. Since it was a bit of a headache to get it to recognize the config file, I'll explain what happened. At first I thought that my .conf location might have been wrong (documentation has typo "next to the /script [script**s**] folder") but it ended up more complicated than that. Running this shed some light:
```
    mp.msg.fatal(this.scriptName);

```
It turned out to be looking for the wrong name due to the folder it was in ('mpv\scripts\mpvDLNA-3.3.0'). The zip file contains a folder with a version number, and thus actually needing to be named **mpvDLNA_3_3_0.conf** to get a match. This should either be renamed to 'mpvDLNA' or add documentation to do so. (Could also search in code.)

I've seen [/script-opts](https://github.com/mpv-player/mpv/blob/master/player/lua/options.lua#L59) used many more times than /script-settings, this should be added as a safeguard as well probably (i put it in my own Options.js)
```
        this.configFile = mp.find_config_file('script-settings/'+this.scriptName+'.conf');
        if (!this.configFile) // Try legacy settings location as fallback.
			this.configFile = mp.find_config_file('script-opts/'+this.scriptName+'.conf');
        if (!this.configFile) // Try legacy settings location as fallback.
            this.configFile = mp.find_config_file('lua-settings/'+this.scriptName+'.conf');
```

Thanks for the quick fix!

**Comment by chachmu** [comment]
Whoops, I didn't realize that the github release was renaming the folder. I added instructions in the documentation to rename the folder and rewrote the sentence about the location of the `\scripts` folder to hopefully be more clear. I also added your suggestion about the `\script-opts` location for the config file.

As for not being able to find the SimpleDLNA server when running it with the `-v music` filter, I still can't replicate that issue. Increasing the timeout has usually worked for me when the DLNA server doesn't immediately appear. The node count shouldn't affect searching for DLNA servers, it just effects how many media files/folders/etc mpvDLNA will fetch from the DLNA server in a single request. Since mpvDLNA currently only makes one request per folder you might not be able to see everything in a folder if the number of items exceeds the number set for the node count.

The only thing I can really think of that would potentially be causing mpvDLNA to not see the server would be if adding the filter causes it to broadcast a different device type or something. You might try checking in http://192.168.1.123:12345/mm-1/description.xml and seeing what the deviceType shows, mpvDLNA expects it to contain `MediaServer` somewhere in the tag. Most DLNA media servers I have seen so far use this tag:`<deviceType>urn:schemas-upnp-org:device:MediaServer:1</deviceType>`.

**Comment by goombapatrol** [comment]
Yeah it looks normal to me, no idea why it's missing it in the scan.
```
<deviceType>urn:schemas-upnp-org:device:MediaServer:1</deviceType>
```
Tried timeout 10 minutes, still no find. (It picks up filterless in just 2 sec).

Cool to see folder name fixed, thanks!

**Comment by chachmu** [comment]
As far as I can tell the remaining problem is probably in either upnpclient or SimpleMediaServer so I'm going to go ahead and close this issue. Feel free to reopen it if you figure something out!
