### ISSUE TITLE
Error on start

### ISSUE THREAD

**Issue by alexunderboots** [chachmu/mpvDLNA#7]
mac os 10.15.7
Error: Unable to find a correctly configuration python call: in the following option: python3,python,python3

ls -R
input.conf	script-settings	scripts

./script-settings:
mpvDLNA.conf

./scripts:
mpvDLNA		webtorrent.js

./scripts/mpvDLNA:
LICENSE		README.md	main.js		modules.js	mpvDLNA.py

./scripts/mpvDLNA/modules.js:
AssFormat.js		MicroUtils.js		Options.js		README.md		SelectionMenu.js

**Comment by chachmu** [comment]
It looks like mpvDLNA is having an issue getting python to work on your system. Can you check if you have it installed and if you can run python from the terminal? 

If you do have a working python install and mpvDLNA still doesn't work then try running mpv with the `--msg-level=mpvDLNA=trace` argument to get a more detailed error log and post it here so we can figure out what else might be causing the issue.

**Comment by alexunderboots** [comment]
ln -s "$HOME/.config/mpv" "$HOME/.mpv" (app and homebrew)

python -V                                       
Python 3.7.9

mpv --msg-level=mpvDLNA=trace (homebrew)
Warning, two config dirs found:
   /Volumes/XXX/alexunderboots2021/.config/mpv (main)
   /Volumes/XXX/alexunderboots2021/.mpv (bogus)
You should merge or delete the second one.
mpv 0.34.1 Copyright © 2000-2021 mpv/MPlayer/mplayer2 projects
 built on Thu Feb  3 03:14:08 UTC 2022
FFmpeg library versions:
   libavutil       56.70.100
   libavcodec      58.134.100
   libavformat     58.76.100
   libswscale      5.9.100
   libavfilter     7.110.100
   libswresample   3.9.100
FFmpeg version: 4.4.2

Usage:   mpv [options] [url|path/]filename

Basic options:
 --start=<time>    seek to given (percent, seconds, or hh:mm:ss) position
 --no-audio        do not play sound
 --no-video        do not play video
 --fs              fullscreen playback
 --sub-file=<file> specify subtitle file to use
 --playlist=<file> specify playlist file

 --list-options    list all mpv options
 --h=<string>      print options which contain the given string in their name

**Comment by chachmu** [comment]
For some reason it doesn't look like mpvDLNA started during that command. Could you try one more time with the message level argument and use mpv to actually open a file? Hopefully that should make mpvDLNA try to start up.

**Comment by alexunderboots** [comment]
**app mpv**
The error only occurs when running the app version through the Finder, but not when running the executable from the "package contents"

**app mpv package contents**
keyboard shortcuts work, sees servers, opens files, does not support Russian letters in the names

Warning, two config dirs found:
   /Volumes/XXX/alexunderboots2021/.mpv (main)
   /Volumes/XXX/alexunderboots2021/.config/mpv (bogus)
You should merge or delete the second one.
[mpvDLNA] Loading javascript /Volumes/XXX/alexunderboots2021/.config/mpv/scripts/mpvDLNA/main.js...
[mpvDLNA] Loading file @/defaults.js
[mpvDLNA] Reading file '@/defaults.js'
[mpvDLNA] Reading file '/Volumes/XXX/alexunderboots2021/.mpv/.init.js'
[mpvDLNA] Loading file /Volumes/XXX/alexunderboots2021/.config/mpv/scripts/mpvDLNA/main.js
[mpvDLNA] Reading file '/Volumes/XXX/alexunderboots2021/.config/mpv/scripts/mpvDLNA/main.js'
[mpvDLNA] Reading file '/Volumes/XXX/alexunderboots2021/.config/mpv/scripts/mpvDLNA/modules/Options.js'
[mpvDLNA] Reading file '/Volumes/XXX/alexunderboots2021/.config/mpv/scripts/mpvDLNA/modules.js/Options.js'
[mpvDLNA] Reading file '/Volumes/XXX/alexunderboots2021/.config/mpv/scripts/mpvDLNA/modules.js/Options.js'
[mpvDLNA] Reading file '/Volumes/XXX/alexunderboots2021/.config/mpv/scripts/mpvDLNA/modules/AssFormat.js'
[mpvDLNA] Reading file '/Volumes/XXX/alexunderboots2021/.config/mpv/scripts/mpvDLNA/modules.js/AssFormat.js'
[mpvDLNA] Reading file '/Volumes/XXX/alexunderboots2021/.config/mpv/scripts/mpvDLNA/modules.js/AssFormat.js'
[mpvDLNA] Reading file '/Volumes/XXX/alexunderboots2021/.config/mpv/scripts/mpvDLNA/modules/MicroUtils.js'
[mpvDLNA] Reading file '/Volumes/XXX/alexunderboots2021/.config/mpv/scripts/mpvDLNA/modules.js/MicroUtils.js'
[mpvDLNA] Reading file '/Volumes/XXX/alexunderboots2021/.config/mpv/scripts/mpvDLNA/modules.js/MicroUtils.js'
[mpvDLNA] Reading file '/Volumes/XXX/alexunderboots2021/.config/mpv/scripts/mpvDLNA/modules/SelectionMenu.js'
[mpvDLNA] Reading file '/Volumes/XXX/alexunderboots2021/.config/mpv/scripts/mpvDLNA/modules.js/SelectionMenu.js'
[mpvDLNA] Reading file '/Volumes/XXX/alexunderboots2021/.config/mpv/scripts/mpvDLNA/modules.js/SelectionMenu.js'
[mpvDLNA] Reading options for mpvDLNA.
[mpvDLNA] Reading file '/Volumes/XXX/alexunderboots2021/.mpv/script-settings/mpvDLNA.conf'
[mpvDLNA] "/Volumes/XXX/alexunderboots2021/.mpv/script-settings/mpvDLNA.conf": Ignoring unknown key "timeout ".
[mpvDLNA] mpvDLNA.py -w: 
[mpvDLNA] mpvDLNA.py -w: 


**homebrew mpv**
keyboard shortcuts work, sees servers, opens files, does not support Russian letters in the names

Warning, two config dirs found:
   /Volumes/XXX/alexunderboots2021/.config/mpv (main)
   /Volumes/XXX/alexunderboots2021/.mpv (bogus)
You should merge or delete the second one.
[mpvDLNA] Loading javascript /Volumes/XXX/alexunderboots2021/.mpv/scripts/mpvDLNA/main.js...
[mpvDLNA] Loading file @/defaults.js
[mpvDLNA] Reading file '@/defaults.js'
[mpvDLNA] Loading file /Volumes/XXX/alexunderboots2021/.mpv/scripts/mpvDLNA/main.js
[mpvDLNA] Reading file '/Volumes/XXX/alexunderboots2021/.mpv/scripts/mpvDLNA/main.js'
[mpvDLNA] Reading file '/Volumes/XXX/alexunderboots2021/.mpv/scripts/mpvDLNA/modules/Options.js'
[mpvDLNA] Reading file '/Volumes/XXX/alexunderboots2021/.mpv/scripts/mpvDLNA/modules.js/Options.js'
[mpvDLNA] Reading file '/Volumes/XXX/alexunderboots2021/.mpv/scripts/mpvDLNA/modules.js/Options.js'
[mpvDLNA] Reading file '/Volumes/XXX/alexunderboots2021/.mpv/scripts/mpvDLNA/modules/AssFormat.js'
[mpvDLNA] Reading file '/Volumes/XXX/alexunderboots2021/.mpv/scripts/mpvDLNA/modules.js/AssFormat.js'
[mpvDLNA] Reading file '/Volumes/XXX/alexunderboots2021/.mpv/scripts/mpvDLNA/modules.js/AssFormat.js'
[mpvDLNA] Reading file '/Volumes/XXX/alexunderboots2021/.mpv/scripts/mpvDLNA/modules/MicroUtils.js'
[mpvDLNA] Reading file '/Volumes/XXX/alexunderboots2021/.mpv/scripts/mpvDLNA/modules.js/MicroUtils.js'
[mpvDLNA] Reading file '/Volumes/XXX/alexunderboots2021/.mpv/scripts/mpvDLNA/modules.js/MicroUtils.js'
[mpvDLNA] Reading file '/Volumes/XXX/alexunderboots2021/.mpv/scripts/mpvDLNA/modules/SelectionMenu.js'
[mpvDLNA] Reading file '/Volumes/XXX/alexunderboots2021/.mpv/scripts/mpvDLNA/modules.js/SelectionMenu.js'
[mpvDLNA] Reading file '/Volumes/XXX/alexunderboots2021/.mpv/scripts/mpvDLNA/modules.js/SelectionMenu.js'
[mpvDLNA] Reading options for mpvDLNA.
[mpvDLNA] Reading file '/Volumes/XXX/alexunderboots2021/.config/mpv/script-settings/mpvDLNA.conf'
[mpvDLNA] "/Volumes/XXX/alexunderboots2021/.config/mpv/script-settings/mpvDLNA.conf": Ignoring unknown key "timeout ".
[mpvDLNA] mpvDLNA.py -w: 
[mpvDLNA] mpvDLNA.py -w: 
 (+) Video --vid=1 (*) (h264 1280x720 29.970fps)
 (+) Audio --aid=1 (*) (aac 2ch 48000Hz)
AO: [coreaudio] 48000Hz stereo 2ch floatp
VO: [libmpv] 1280x720 yuv420p
(Paused) AV: 00:00:01 / 00:00:19 (10%) A-V:  0.000

**Comment by chachmu** [comment]
It sounds like the finder is launching the application with some sort of different environment than the command line version. I haven't used macOS in a long time so I'm not really sure what you can do to fix this but I guess you might be able to find a way to edit the properties of the mpv application somehow.

As for the issues with Russian characters I can try to look into that although mpvDLNA has had a lot of issues with unicode characters in the past so I can't say for sure if I will be able to get that working.

**Comment by chachmu** [comment]
I tried to get Russian characters working and unfortunately mpv doesn't properly support receiving unicode characters from commands that it runs so I don't think there is going to be anything I can do to support non-ASCII characters.

**Comment by DrMoebius** [comment]
> It sounds like the finder is launching the application with some sort of different environment than the command line version. I haven't used macOS in a long time so I'm not really sure what you can do to fix this but I guess you might be able to find a way to edit the properties of the mpv application somehow.
> 
MacOS 12.6

Did not check what the default values are, but I managed to fix this by running `launchctl config user path /usr/local/bin:/usr/bin:/usr/sbin` in the terminal.

**Comment by chachmu** [comment]
Good news! Thanks to @hyousatsu UTF-8 encoding works so that should add support for Russian characters as well as any other unicode characters. As for the environment issue it seems like the issua has been fixed so I am going to close this issue, feel free to reopen it if you are still having any of these problems after installing the updated version of mpvDLNA.
