### ISSUE TITLE
Filenames with UTF-8 special characters are broken (regression)

### ISSUE THREAD

**Issue by goombapatrol** [chachmu/mpvDLNA#9]
Hey. Tried out latest build [mpvDLNA 3.4.0](https://github.com/chachmu/mpvDLNA/releases/tag/v3.4.0) and noticed that it started spitting out errors (and breaking script, it's not just a warning). After some trial and error i traced it to a filename with special “ (U+201C) mark. The other special characters i tested all failed as well, such as Þ Thorn.

I saw a pull request specifically UTF-8-related and that you had some previous issues https://github.com/chachmu/mpvDLNA/pull/8 - but just wanted to bring your attention to the fact that this isn't resolved in latest build.

The offending files are in top level directory of the folder, if that's useful info.

```
[mpvDLNA] TypeError: cannot convert undefined to object
[mpvDLNA]       at C:\Users\foo\AppData\Roaming/mpv/scripts/mpvDLNA/main.js:1115
[mpvDLNA]       at C:\Users\foo\AppData\Roaming/mpv/scripts/mpvDLNA/main.js:1179
[mpvDLNA]       at C:\Users\foo\AppData\Roaming/mpv/scripts/mpvDLNA/main.js:1294
[mpvDLNA]       at C:\Users\foo\AppData\Roaming/mpv/scripts/mpvDLNA/modules.js/SelectionMenu.js:310
[mpvDLNA]       at C:\Users\foo\AppData\Roaming/mpv/scripts/mpvDLNA/modules.js/SelectionMenu.js:243
[mpvDLNA]       at key_cb (@/defaults.js:347)
[mpvDLNA]       at dispatch_key_binding (@/defaults.js:274)
[mpvDLNA]       at Function.prototype.apply (native)
[mpvDLNA]       at dispatch_message (@/defaults.js:122)
[mpvDLNA]       at dispatch_event (@/defaults.js:52)
[mpvDLNA]       at mp_event_loop (@/defaults.js:762)
[mpvDLNA]       at run_script (native)
```

Previous Version 3.3.1 handles these files just fine with SimpleDLNA.

--------

**Edit:** Tested out with a different DLNA server (running on KODI) and got error with **3.3.1**, but NOT with 3.4.0, which worked correctly in that case.

So i see there was a fix - but your fix ended up breaking mine which wasn't previously having any issue. Any ideas or other info i can provide?

**Comment by chachmu** [comment]
Thanks for pointing that out, I'll try to take a look at it this weekend.

**Comment by chachmu** [comment]
I did my initial testing for the 3.4.0 fix on SimpleDLNA as well so it's weird that its causing issues for you. I also just tested those 2 specific unicode characters with SimpleDLNA on Windows and it seems to work. What operating system and python version are you using?

**Comment by chachmu** [comment]
Is it possible that SimpleDLNA wasn't actually able to provide access to the file? I tried requesting a file that SimpleDLNA didn't have and got the same error on the same lines of code.

**Comment by goombapatrol** [comment]
> I did my initial testing for the 3.4.0 fix on SimpleDLNA as well so it's weird that its causing issues for you. I also just tested those 2 specific unicode characters with SimpleDLNA on Windows and it seems to work. What operating system and python version are you using?

Python version 3.8 / Windows 7

(And the file was accessible, yes)

**Comment by chachmu** [comment]
Ok, I tried SimpleDLNA again on a different windows computer with python 3.7 and still can't get an error. Could you try using mpvDLNA.py to browse directly to the file that is causing the problem and show what the output is? Basically you can run:

`python mpvDLNA.py -b http://localhost:1900/mm-1/description.xml 0` (the address for your SimpleDLNA server may be different but it should print it in the gui when you launch it). 

This will make the script print a list of folder and file names and their associated id that are in the current id you fed it (0 in this case which refers to the starting folder). Then you can work your way to the file you are testing with by swapping it for the id of the folder/file you want to move to. I think SimpleDLNA formats its ids as a string of capital letters and numbers i.e. `778EFAEF`

**Comment by goombapatrol** [comment]
Zero idea why but it's working now and i can't recreate it either. The server PC had been on for a while, and power went out - when it came back on it was fine... weird.

Thanks so much for taking the time to look into this, ill mark as resolved unless something pops up.
